version: "3"

services:
    mongodb:
      image: mongo:latest
      container_name: mongodb
      # restart: always
      ports:
        - '27018-27020:27017'
      # hostname: mongodb
      environment:
        - MONGO_INITDB_DATABASE=pruebas #db a crear
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
      volumes:
        - ./mongo-entrypoint:/docker-entrypoint-initdb.d
        # named volumes
       # - mongodb:/var/lib/data/db
        - mongoconfig:/var/lib/data/configdb
        # binded volumes
        - ./persistHere:/var/lib/data/db
      networks:
        - mongodb_net
    mongoclient:
      image: mongoclient/mongoclient:latest
      container_name: mongoclient
      # restart: always
      hostname: mongoclient
      environment:
        - MONGO_SERVER=mongodb
        - MONGO_INITDB_DATABASE=pruebas
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
      depends_on:
        - mongodb
      networks:
        - mongodb_net
      ports:
        - 83:3000

# default dir on Unbuntu: /var/lib/docker/volumes
volumes:
  mongodb:
  mongoconfig:

networks:
  mongodb_net:
    driver: bridge