
version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres14
    restart: always
    ports: 
      - "5433:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - pgvolume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - postgres

volumes:
  pgvolume: