version: '3'
services:

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    command: '--default-authentication-plugin=mysql_native_password'
    env_file: .env
    environment:
       MYSQL_DATABASE: wordpress
    volumes:
      - dbdata:/var/lib/mysql

  wordpress:
    image: wordpress:5-fpm-alpine
    depends_on:
      - db
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
#      - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
#        lo mismo si tuviera plugins 
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
        # suministrar el .conf
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d
        # tras generar el cerbot descomentar:
      # - certbotdata:/etc/letsencrypt
  
  # primera vez comentar todo el servicio certbot
  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbotdata:/etc/letsencrypt
  #     - wordpress:/var/www/html
  #   # tras generar correctamente el certificado, comentar el comando siguiente:
  #   command: certonly --webroot --webroot-path=/var/www/html --email email@email.com --agree-tos --no-eff-email --force-renewal -d dominio.com -d www.dominio.com

# add this volumes section here  <==================
volumes:
  wordpress:
  dbdata:
  # certbotdata:

